# Generated by Django 3.0.6 on 2020-05-24 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20200516_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
