# Generated by Django 3.0.6 on 2020-05-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_auto_20200524_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='date',
            new_name='datetime',
        ),
    ]
