# Generated by Django 3.0.6 on 2020-05-24 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20200524_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_url', models.URLField(default=None, max_length=500, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
