# Generated by Django 3.0.6 on 2020-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_memoryfile_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryfile',
            name='media_type',
            field=models.CharField(choices=[('A', 'audio'), ('V', 'video'), ('I', 'image'), ('Y', 'youtube')], max_length=1),
        ),
    ]
