# Generated by Django 3.0.6 on 2020-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_auto_20200528_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryfile',
            name='media_type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image'), ('youtube', 'youtube')], max_length=10),
        ),
    ]
