# Generated by Django 3.0.6 on 2020-06-01 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0011_auto_20200530_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='datetime',
        ),
        migrations.AddField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
